/* eslint-disable */
// This file is generated by scripts/generate-data.mjs

export type GuideStub = {
  title: string;
  slug: string;
  excerpt: string;
  category: string;
  datePublished: string;
};

export const guides: GuideStub[] = [
  {
    "title": "Renting in Melbourne for first-time renters",
    "slug": "renting-in-melbourne-for-first-time-renters",
    "excerpt": "Renting in Melbourne for first-time renters with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Getting Started",
    "datePublished": "2026-01-03"
  },
  {
    "title": "How much rent can you afford in Victoria?",
    "slug": "how-much-rent-can-you-afford-in-victoria",
    "excerpt": "How much rent can you afford in Victoria? with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Budgeting",
    "datePublished": "2026-01-04"
  },
  {
    "title": "Understanding bond, advance rent, and moving costs",
    "slug": "understanding-bond-advance-rent-and-moving-costs",
    "excerpt": "Understanding bond, advance rent, and moving costs with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Budgeting",
    "datePublished": "2026-01-05"
  },
  {
    "title": "Suburb checklist for Melbourne apartment hunters",
    "slug": "suburb-checklist-for-melbourne-apartment-hunters",
    "excerpt": "Suburb checklist for Melbourne apartment hunters with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Suburb Research",
    "datePublished": "2026-01-06"
  },
  {
    "title": "Questions to ask at a rental inspection",
    "slug": "questions-to-ask-at-a-rental-inspection",
    "excerpt": "Questions to ask at a rental inspection with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Inspections",
    "datePublished": "2026-01-07"
  },
  {
    "title": "How to compare rental value between suburbs",
    "slug": "how-to-compare-rental-value-between-suburbs",
    "excerpt": "How to compare rental value between suburbs with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Suburb Research",
    "datePublished": "2026-01-08"
  },
  {
    "title": "What documents renters need before applying",
    "slug": "what-documents-renters-need-before-applying",
    "excerpt": "What documents renters need before applying with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Applications",
    "datePublished": "2026-01-09"
  },
  {
    "title": "How to improve your rental application",
    "slug": "how-to-improve-your-rental-application",
    "excerpt": "How to improve your rental application with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Applications",
    "datePublished": "2026-01-10"
  },
  {
    "title": "Private landlord vs agency rentals in Victoria",
    "slug": "private-landlord-vs-agency-rentals-in-victoria",
    "excerpt": "Private landlord vs agency rentals in Victoria with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Applications",
    "datePublished": "2026-01-11"
  },
  {
    "title": "Best inner-city suburbs for renters who commute",
    "slug": "best-inner-city-suburbs-for-renters-who-commute",
    "excerpt": "Best inner-city suburbs for renters who commute with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Suburb Research",
    "datePublished": "2026-01-12"
  },
  {
    "title": "Best family-friendly rental suburbs in the east",
    "slug": "best-family-friendly-rental-suburbs-in-the-east",
    "excerpt": "Best family-friendly rental suburbs in the east with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Suburb Research",
    "datePublished": "2026-01-13"
  },
  {
    "title": "Affordable rental suburbs in Melbourne's west",
    "slug": "affordable-rental-suburbs-in-melbourne-s-west",
    "excerpt": "Affordable rental suburbs in Melbourne's west with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Suburb Research",
    "datePublished": "2026-01-14"
  },
  {
    "title": "What to expect from a Victorian lease agreement",
    "slug": "what-to-expect-from-a-victorian-lease-agreement",
    "excerpt": "What to expect from a Victorian lease agreement with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Tenancy",
    "datePublished": "2026-01-15"
  },
  {
    "title": "Condition reports explained for Victorian tenants",
    "slug": "condition-reports-explained-for-victorian-tenants",
    "excerpt": "Condition reports explained for Victorian tenants with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Tenancy",
    "datePublished": "2026-01-16"
  },
  {
    "title": "Rent increase rules in Victoria",
    "slug": "rent-increase-rules-in-victoria",
    "excerpt": "Rent increase rules in Victoria with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Tenancy",
    "datePublished": "2026-01-17"
  },
  {
    "title": "What to do if a rental listing looks overpriced",
    "slug": "what-to-do-if-a-rental-listing-looks-overpriced",
    "excerpt": "What to do if a rental listing looks overpriced with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Pricing",
    "datePublished": "2026-01-18"
  },
  {
    "title": "How to inspect a unit for hidden maintenance issues",
    "slug": "how-to-inspect-a-unit-for-hidden-maintenance-issues",
    "excerpt": "How to inspect a unit for hidden maintenance issues with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Inspections",
    "datePublished": "2026-01-19"
  },
  {
    "title": "Choosing between an apartment, unit, and townhouse",
    "slug": "choosing-between-an-apartment-unit-and-townhouse",
    "excerpt": "Choosing between an apartment, unit, and townhouse with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Property Types",
    "datePublished": "2026-01-20"
  },
  {
    "title": "How transport access changes rental value",
    "slug": "how-transport-access-changes-rental-value",
    "excerpt": "How transport access changes rental value with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Pricing",
    "datePublished": "2026-01-21"
  },
  {
    "title": "What renters should know about pet applications",
    "slug": "what-renters-should-know-about-pet-applications",
    "excerpt": "What renters should know about pet applications with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Applications",
    "datePublished": "2026-01-22"
  },
  {
    "title": "How to budget for utilities in a Melbourne rental",
    "slug": "how-to-budget-for-utilities-in-a-melbourne-rental",
    "excerpt": "How to budget for utilities in a Melbourne rental with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Budgeting",
    "datePublished": "2026-01-23"
  },
  {
    "title": "Best renter tools for comparing weekly costs",
    "slug": "best-renter-tools-for-comparing-weekly-costs",
    "excerpt": "Best renter tools for comparing weekly costs with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Budgeting",
    "datePublished": "2026-01-24"
  },
  {
    "title": "How to shortlist suburbs by lifestyle and price",
    "slug": "how-to-shortlist-suburbs-by-lifestyle-and-price",
    "excerpt": "How to shortlist suburbs by lifestyle and price with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Suburb Research",
    "datePublished": "2026-01-25"
  },
  {
    "title": "What makes South Yarra rents higher than average",
    "slug": "what-makes-south-yarra-rents-higher-than-average",
    "excerpt": "What makes South Yarra rents higher than average with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Pricing",
    "datePublished": "2026-01-26"
  },
  {
    "title": "What makes Brunswick popular with renters",
    "slug": "what-makes-brunswick-popular-with-renters",
    "excerpt": "What makes Brunswick popular with renters with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Suburb Research",
    "datePublished": "2026-01-27"
  },
  {
    "title": "How to read a rental listing before you enquire",
    "slug": "how-to-read-a-rental-listing-before-you-enquire",
    "excerpt": "How to read a rental listing before you enquire with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Listings",
    "datePublished": "2026-01-28"
  },
  {
    "title": "What counts as urgent repairs in Victoria",
    "slug": "what-counts-as-urgent-repairs-in-victoria",
    "excerpt": "What counts as urgent repairs in Victoria with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Tenancy",
    "datePublished": "2026-01-29"
  },
  {
    "title": "How to negotiate a lease start date",
    "slug": "how-to-negotiate-a-lease-start-date",
    "excerpt": "How to negotiate a lease start date with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Applications",
    "datePublished": "2026-01-30"
  },
  {
    "title": "End of lease cleaning expectations for tenants",
    "slug": "end-of-lease-cleaning-expectations-for-tenants",
    "excerpt": "End of lease cleaning expectations for tenants with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Tenancy",
    "datePublished": "2026-01-31"
  },
  {
    "title": "How to decide between bayside and inner north rentals",
    "slug": "how-to-decide-between-bayside-and-inner-north-rentals",
    "excerpt": "How to decide between bayside and inner north rentals with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Suburb Research",
    "datePublished": "2026-02-01"
  },
  {
    "title": "Rental application mistakes to avoid",
    "slug": "rental-application-mistakes-to-avoid",
    "excerpt": "Rental application mistakes to avoid with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Applications",
    "datePublished": "2026-02-02"
  },
  {
    "title": "How to compare listings by effective weekly cost",
    "slug": "how-to-compare-listings-by-effective-weekly-cost",
    "excerpt": "How to compare listings by effective weekly cost with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Pricing",
    "datePublished": "2026-02-03"
  },
  {
    "title": "Living near a train line: trade-offs for renters",
    "slug": "living-near-a-train-line-trade-offs-for-renters",
    "excerpt": "Living near a train line: trade-offs for renters with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Lifestyle",
    "datePublished": "2026-02-04"
  },
  {
    "title": "How students can find rentals near universities",
    "slug": "how-students-can-find-rentals-near-universities",
    "excerpt": "How students can find rentals near universities with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Lifestyle",
    "datePublished": "2026-02-05"
  },
  {
    "title": "Is furnished or unfurnished better for your budget?",
    "slug": "is-furnished-or-unfurnished-better-for-your-budget",
    "excerpt": "Is furnished or unfurnished better for your budget? with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Budgeting",
    "datePublished": "2026-02-06"
  },
  {
    "title": "How to find rentals with parking in inner Melbourne",
    "slug": "how-to-find-rentals-with-parking-in-inner-melbourne",
    "excerpt": "How to find rentals with parking in inner Melbourne with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Listings",
    "datePublished": "2026-02-07"
  },
  {
    "title": "What to inspect in older Victorian homes",
    "slug": "what-to-inspect-in-older-victorian-homes",
    "excerpt": "What to inspect in older Victorian homes with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Inspections",
    "datePublished": "2026-02-08"
  },
  {
    "title": "How to find pet-friendly apartments in Melbourne",
    "slug": "how-to-find-pet-friendly-apartments-in-melbourne",
    "excerpt": "How to find pet-friendly apartments in Melbourne with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Listings",
    "datePublished": "2026-02-09"
  },
  {
    "title": "Checklist for moving into a new rental",
    "slug": "checklist-for-moving-into-a-new-rental",
    "excerpt": "Checklist for moving into a new rental with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Moving",
    "datePublished": "2026-02-10"
  },
  {
    "title": "How to calculate total upfront moving costs",
    "slug": "how-to-calculate-total-upfront-moving-costs",
    "excerpt": "How to calculate total upfront moving costs with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Budgeting",
    "datePublished": "2026-02-11"
  },
  {
    "title": "Why median rent matters when comparing suburbs",
    "slug": "why-median-rent-matters-when-comparing-suburbs",
    "excerpt": "Why median rent matters when comparing suburbs with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Pricing",
    "datePublished": "2026-02-12"
  },
  {
    "title": "How to track new rentals in your target suburb",
    "slug": "how-to-track-new-rentals-in-your-target-suburb",
    "excerpt": "How to track new rentals in your target suburb with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Search",
    "datePublished": "2026-02-13"
  },
  {
    "title": "How to prepare for Saturday inspection runs",
    "slug": "how-to-prepare-for-saturday-inspection-runs",
    "excerpt": "How to prepare for Saturday inspection runs with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Inspections",
    "datePublished": "2026-02-14"
  },
  {
    "title": "When to choose regional Victoria over Melbourne",
    "slug": "when-to-choose-regional-victoria-over-melbourne",
    "excerpt": "When to choose regional Victoria over Melbourne with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Regional",
    "datePublished": "2026-02-15"
  },
  {
    "title": "Best suburbs for beachside renters on a budget",
    "slug": "best-suburbs-for-beachside-renters-on-a-budget",
    "excerpt": "Best suburbs for beachside renters on a budget with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Suburb Research",
    "datePublished": "2026-02-16"
  },
  {
    "title": "Best suburbs for renters who work from home",
    "slug": "best-suburbs-for-renters-who-work-from-home",
    "excerpt": "Best suburbs for renters who work from home with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Lifestyle",
    "datePublished": "2026-02-17"
  },
  {
    "title": "How school zones affect rental demand",
    "slug": "how-school-zones-affect-rental-demand",
    "excerpt": "How school zones affect rental demand with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Pricing",
    "datePublished": "2026-02-18"
  },
  {
    "title": "What renters should ask about internet and mobile coverage",
    "slug": "what-renters-should-ask-about-internet-and-mobile-coverage",
    "excerpt": "What renters should ask about internet and mobile coverage with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Listings",
    "datePublished": "2026-02-19"
  },
  {
    "title": "Guide to townhouse rentals in Melbourne's growth areas",
    "slug": "guide-to-townhouse-rentals-in-melbourne-s-growth-areas",
    "excerpt": "Guide to townhouse rentals in Melbourne's growth areas with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Property Types",
    "datePublished": "2026-02-20"
  },
  {
    "title": "How to evaluate storage space before you apply",
    "slug": "how-to-evaluate-storage-space-before-you-apply",
    "excerpt": "How to evaluate storage space before you apply with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Inspections",
    "datePublished": "2026-02-21"
  },
  {
    "title": "Guide to renting in Geelong",
    "slug": "guide-to-renting-in-geelong",
    "excerpt": "Guide to renting in Geelong with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Regional",
    "datePublished": "2026-02-22"
  },
  {
    "title": "Guide to renting in Ballarat",
    "slug": "guide-to-renting-in-ballarat",
    "excerpt": "Guide to renting in Ballarat with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Regional",
    "datePublished": "2026-02-23"
  },
  {
    "title": "Guide to renting in Bendigo",
    "slug": "guide-to-renting-in-bendigo",
    "excerpt": "Guide to renting in Bendigo with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Regional",
    "datePublished": "2026-02-24"
  },
  {
    "title": "How to compare walkability between suburbs",
    "slug": "how-to-compare-walkability-between-suburbs",
    "excerpt": "How to compare walkability between suburbs with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Suburb Research",
    "datePublished": "2026-02-25"
  },
  {
    "title": "How to shortlist a suburb in one afternoon",
    "slug": "how-to-shortlist-a-suburb-in-one-afternoon",
    "excerpt": "How to shortlist a suburb in one afternoon with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Suburb Research",
    "datePublished": "2026-02-26"
  },
  {
    "title": "Pros and cons of renting in Melbourne CBD",
    "slug": "pros-and-cons-of-renting-in-melbourne-cbd",
    "excerpt": "Pros and cons of renting in Melbourne CBD with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Suburb Research",
    "datePublished": "2026-02-27"
  },
  {
    "title": "How to estimate commute costs by suburb",
    "slug": "how-to-estimate-commute-costs-by-suburb",
    "excerpt": "How to estimate commute costs by suburb with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Budgeting",
    "datePublished": "2026-02-28"
  },
  {
    "title": "What makes a listing enquiry stand out",
    "slug": "what-makes-a-listing-enquiry-stand-out",
    "excerpt": "What makes a listing enquiry stand out with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Applications",
    "datePublished": "2026-03-01"
  },
  {
    "title": "How to evaluate value in fast-moving rental markets",
    "slug": "how-to-evaluate-value-in-fast-moving-rental-markets",
    "excerpt": "How to evaluate value in fast-moving rental markets with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Pricing",
    "datePublished": "2026-03-02"
  },
  {
    "title": "Guide to regional rental inspections in Victoria",
    "slug": "guide-to-regional-rental-inspections-in-victoria",
    "excerpt": "Guide to regional rental inspections in Victoria with practical Victorian rental advice, suburb context, and budget tips for tenants comparing listings in Melbourne and regional Victoria.",
    "category": "Regional",
    "datePublished": "2026-03-03"
  },
  {
    "title": "Cheapest Suburbs to Rent in Sydney 2026 — Full Affordability Guide",
    "slug": "cheapest-suburbs-to-rent-sydney-2026",
    "excerpt": "Discover the 15 cheapest suburbs to rent in Sydney in 2026. Median rents, transport links, suburb profiles, and practical tips for finding affordable rentals across Greater Sydney.",
    "category": "Suburb Research",
    "datePublished": "2026-03-31"
  },
  {
    "title": "How to Find a Rental in Brisbane 2026: Complete Step-by-Step Guide",
    "slug": "how-to-find-rental-brisbane-2026",
    "excerpt": "Learn how to find a rental in Brisbane in 2026 with this complete guide covering the best suburbs by budget, application tips, pet-friendly areas, flood zones, and common mistakes to avoid.",
    "category": "Getting Started",
    "datePublished": "2026-03-31"
  }
] as GuideStub[];
